services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    env_file: docker.env
    depends_on:
      - worker
      - redis
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks: 
      - app_network
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks: 
      - app_network
  
  worker:
    build:
      context: .
    env_file: docker.env
    command: ["celery", "-A", "core.celery", "worker", "-l", "info", "--concurrency=4", "-B","-Q", "default"] 
    volumes:
      - ./:/app 
    depends_on: 
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped
    networks:
      - app_network
  
  flower:
    image: mher/flower
    command: ['celery', '--broker=redis://redis:6379', 'flower', '--port=5555', "--basic-auth=admin@admin.com:admin"]
    ports:
      - "7777:5555"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_network

volumes:
  redis_data:

networks: 
  app_network:
    driver: bridge
