# Generated by Django 5.2 on 2025-05-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleProdcutCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxHandlingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(unique=True)),
                ('end_time', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('remarks', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=300)),
                ('additional_image', models.CharField(max_length=300)),
                ('lifestype_image_link', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=250)),
                ('price', models.CharField()),
                ('sale_price', models.CharField()),
                ('shipping_cost', models.CharField()),
                ('availability', models.CharField(choices=[('IN_S', 'in_stock'), ('OUT_S', 'out_of_stock')], default='OUT_S')),
                ('gtin', models.IntegerField(unique=True)),
                ('product_length', models.CharField(blank=True, null=True)),
                ('product_width', models.CharField(blank=True, null=True)),
                ('product_height', models.CharField(blank=True, null=True)),
                ('product_weight', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('is_bundle', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO')),
                ('model', models.CharField(blank=True, null=True, unique=True)),
                ('condition', models.CharField(choices=[('NEW', 'new'), ('USED', 'used'), ('REFURBISHED', 'refurbished')], default='NEW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='excel_import_export.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.gender')),
                ('google_product_catagories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.googleprodcutcatagory')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.itemgroup')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.material')),
                ('max_handling_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.maxhandlingtime')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.pattern')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='excel_import_export.producttype')),
            ],
        ),
    ]
