# Generated by Django 5.2 on 2025-05-07 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], default='INFO'),
        ),
    ]
