# Generated by Django 5.2 on 2025-05-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0002_logs_created_at_logs_message_logs_remarks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
