# Generated by Django 5.2 on 2025-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0003_rename_logs_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='lifestype_image_link',
            new_name='lifestyle_image_link',
        ),
    ]
