# Generated by Django 5.2 on 2025-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0005_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='googleprodcutcatagory',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='maxhandlingtime',
            name='end_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='maxhandlingtime',
            name='start_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='is_bundle',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(),
        ),
    ]
