# Generated by Django 5.2 on 2025-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0006_alter_brand_name_alter_color_name_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='gtin',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='model',
            field=models.CharField(max_length=250),
        ),
    ]
