# Generated by Django 5.2 on 2025-05-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0007_alter_productitem_gtin_alter_productitem_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='google_product_catagories',
            new_name='google_product_catagory',
        ),
    ]
