# Generated by Django 5.2 on 2025-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0008_rename_google_product_catagories_productitem_google_product_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
