# Generated by Django 5.2 on 2025-05-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0009_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='additional_image',
            new_name='additional_image_link',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='google_product_catagory',
            new_name='google_product_category',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='image',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='item_group',
            new_name='item_group_id',
        ),
    ]
