# Generated by Django 5.2 on 2025-05-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0010_rename_additional_image_productitem_additional_image_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='additional_image_link',
            new_name='additional_image_links',
        ),
    ]
