# Generated by Django 5.2 on 2025-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0011_rename_additional_image_link_productitem_additional_image_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(),
        ),
    ]
