# Generated by Django 5.2 on 2025-05-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0012_alter_log_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at']},
        ),
    ]
