# Generated by Django 5.2 on 2025-05-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import_export', '0013_alter_log_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('SUCCESS', 'SUCCESS')], default='INFO'),
        ),
    ]
