name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Build, Tag, and Push Docker Image
        id: build_and_push  # Set an id to reference outputs
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)

          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/rex9840/export-task:latest \
            -t ghcr.io/rex9840/export-task:$SHORT_SHA \
            --push .

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}

